apiVersion: v1
kind: Service
metadata:
  name: analysis-engine
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "query-lens.labels" . | nindent 4 }}
    app: analysis-engine
spec:
  type: ClusterIP
  selector:
    app: analysis-engine
  ports:
    - name: http
      port: {{ .Values.analysisEngine.service.port }}
      targetPort: 8083
